### ISSUE TITLE
Regressions for string printing/shrinking?

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#135]
First of all: thanks for an incredible effort on the integrated shrinking! 
I apologize for being late to the party - I finally found time to give QCheck2 a quick spin.
This is using  a fresh clone from master - loaded into utop with `#mod_use`.

* Testing a stupid property (all strings are non-empty) fails - but it is unclear that a counterexample is printed:
   ```
   # let t = Test.make ~print:Print.string Gen.string (fun s -> s <> "");;
   # QCheck_base_runner.run_tests ~verbose:true [t];;
   generated error fail pass / total     time test name
   [✗]    6    0    1    5 /  100     0.0s anon_test_5
   
   --- Failure --------------------------------------------------------------------
   
   Test anon_test_5 failed (0 shrink steps):
   
   
   ================================================================================
   failure (1 tests failed, 0 tests errored, ran 1 tests)
   ```
   
   Compared to QCheck1 this may be as simple as adding surrounding string quotes in the (empty) string printer:
   ```
   #open QCheck;;
   # let t = Test.make string (fun s -> s <> "");;
   # QCheck_base_runner.run_tests ~verbose:true [t];;
   random seed: 92576387
   generated error fail pass / total     time test name
   [✗]    1    0    1    0 /  100     0.0s anon_test_1
   
   --- Failure --------------------------------------------------------------------
   
   Test anon_test_1 failed (0 shrink steps):
   
   ""
   ================================================================================
   failure (1 tests failed, 0 tests errored, ran 1 tests)
  ```

* Testing an equally stupid string property (all strings equal their own concatenation) hits another issue:

   ```
   # let t = Test.make ~print:Print.string Gen.string (fun s -> s = s^s);;
   # QCheck_base_runner.run_tests ~verbose:true [t];;
   generated error fail pass / total     time test name
   [ ]    0    0    0    0 /  100     0.0s anon_test_6 (generating)Stack overflow during evaluation (looping recursion?).
   ```
   
   which didn't cause problems prior to integrated shrinking:

   ```
   # let t = Test.make string (fun s -> s = s^s);;
   # QCheck_base_runner.run_tests ~verbose:true [t];;
   generated error fail pass / total     time test name
   [✗]    1    0    1    0 /  100     0.0s anon_test_2
   
   --- Failure --------------------------------------------------------------------
   
   Test anon_test_2 failed (5 shrink steps):
   
   "\210"
   ================================================================================
   failure (1 tests failed, 0 tests errored, ran 1 tests)
   ```

**Comment by c-cube** [comment]
I just checked and qcheck1 is inconsistent in how it handles printing of strings! in `Print` it would not add the quotes, but the arbitrary instances use `Printf.sprintf "%S"` which uses `String.escaped`. Maybe the base printer should be `String.escaped` as well…

For the second one I haven't looked yet.

**Comment by Sir4ur0n** [comment]
So I think I found the root cause of this bug, but I don't know any fix that doesn't dramatically deteriorate performance...

My understanding of OCaml "laziness" of functions + mutable variables was wrong :sweat_smile: I think the bug is [here](https://github.com/c-cube/qcheck/blob/master/src/core/QCheck2.ml#L640):
```ocaml
char_trees_rev := (fun () -> char_tree :: ((!char_trees_rev) ()));
```

I thought `!char_trees_rev` would evaluate to its then-value, but what seems to happen is that it evaluates to itself the first time it is "really" evaluated, which results in an infinite loop (thus the stack overflow).

But fixing it brings us back to the original reason why this function is not a basic "list of chars then converted to a string/bytes": performance.

I tested a bit again with a mutable `list`, with a mutable `Seq.t`, with a `Queue.t`... The performance is everytime between 10 and 20 times slower than QCheck1 string generator.

I am really surprised keeping track of those trees is so expensive, since they are not evaluated yet - as far as I understand. I reckon there is a bit of closures to carry around, but not that expensive :open_mouth: 

Does anyone have an idea to address this? Or do we consider this performance deterioration is "acceptable"?

Note - I just gave it a shot while typing this last sentence - that at least `int` generation seems to also be significantly slower: around 10 times slower than QCheck1 by the look of it.

What's your opinion?

**Comment by c-cube** [comment]
> I thought !char_trees_rev would evaluate to its then-value

indeed, you want:

```ocaml
char_trees_rev := (
  let cur = !char_trees_rev in
  fun () -> char_tree :: cur);
```

The shrinking is, clearly, imposing costs. I think it's possibly because there's a lot more to do, including allocations, whereas `QCheck.Gen.string` is quite lean (it directly allocates bytes of the right size, and assigns bytes one by one).

The real question is, even if generators are slower, does this affect significantly actual test runs.

**Comment by Sir4ur0n** [comment]
> indeed, you want:

Yup that's what I did once I understood my mistake, but then I was back to poor performance :grin: 

> The real question is, even if generators are slower, does this affect significantly actual test runs.

I am more and more reaching the conclusion that indeed, while this 10x number is scary, it's actually not that shocking considering how lean QCheck1 implementation is :smile: 

I'll propose a fix (because currently, string shrinking is plain broken) and let's see if anyone is shocked by the perf toll
