### ISSUE TITLE
make check errors in algotest 1.5.0

### ISSUE THREAD

**Issue by olafhering** [c-cube/qcheck#193]
as noted in mirage/alcotest#331, b065a81661d312fc7bbdbf95fb24229d71991a10 fails `dune runtest` with mirage/alcotest@12889aa7f993ad55434443f1c447a59f18ffc9bf

**Comment by jmid** [comment]
> as noted in [mirage/alcotest#331](https://github.com/mirage/alcotest/pull/331), [b065a81](https://github.com/c-cube/qcheck/commit/b065a81661d312fc7bbdbf95fb24229d71991a10) fails `dune runtest` with [mirage/alcotest@12889aa](https://github.com/mirage/alcotest/commit/12889aa7f993ad55434443f1c447a59f18ffc9bf)

I was a bit puzzled at first since [b065a81](https://github.com/c-cube/qcheck/commit/b065a81661d312fc7bbdbf95fb24229d71991a10) is purely a documentation change.

So, this seems due to whitespace changes as far as I can see, where Alcotest 1.5.0 outputs less than 1.4.0.
Digging a bit, after a string of `grep`s in [example/alcotest/run_alcotest.sh](example/alcotest/run_alcotest.sh) there may be sequences of spaces interleaved with newlines in the result.
- stringing on `| sed 's/[ \t]*$//g' | tr -s "\n"` to strip trailing spaces and remove duplicate newlines seems to work
- one could also pass a `diff`-command to dune that would ignore whitespace differences https://dune.readthedocs.io/en/stable/concepts.html#diffing-and-promotion

**Comment by jmid** [comment]
Fixed by #203
