### ISSUE TITLE
system for reporting messages to the user

### ISSUE THREAD

**Issue by c-cube** [c-cube/qcheck#39]
Sometimes I would like to perform some computation in the property itself (given some inputs), and, in case the property does not hold, print intermediate values, informative things, etc. It's also useful to report values found via `find_example` to give an idea of what is happening.

Last commits added such an API (with `Test.make_full` taking an extended property `ctx -> 'a -> bool`
and a `ctx` that can be used to report messages). I'd like the opinion of @Gbury and @jmid on this API.

**Comment by c-cube** [comment]
It's actually better to provide a way to "fail with messages", I think (especially because during shrinking, messages coming from shrunk instances can therefore be discarded).

**Comment by Gbury** [comment]
About the `ctx` type, thinking about possible future evolutions, would it make sens to make it polymorphic so that `test.make_full` takes a `'a ctx -> 'a -> bool`  ? In which case, the generated element the law is tested on could event be integrated into the context so that it becomes `'a ctx -> bool`.

I'm not sure whether this is a good idea, or even what it would be used for (maybe storing counter-examples, failed shrinking counter-examples or even used for storing found examples as mentioned in #31 ?), but it just stroke me as a possibly interesting alternative design.

**Comment by c-cube** [comment]
The big problem is retrocompatibility (and in a way, simplicity). The new design with an exception to fail with error is a bit more KISS imho.

**Comment by jmid** [comment]
Sorry for again(!) being late to the party. On the positive side, I was attending TFP spreading the word about how QCheck was useful to locate the Patricia tree bug :-)
Not sure I have much to add here though. I had a recent situation where I ended up printing the input values causing a property to fail (also during shrinking). This was useful in debugging an issue with a non-trivial shrinker. If I understand you correctly, this new API could come in handy in such situations.

**Comment by c-cube** [comment]
Yes, the point is to be able to fail with a message that can use all the information available in the test (not just the input values) :-)

**Comment by c-cube** [comment]
ok, after some usage the new `Test.fail_report{,f}` is convenient. I think it's sufficient to give more details in case of failure.
