### ISSUE TITLE
Adding a guard in Gen

### ISSUE THREAD

**Issue by nicoTolly** [c-cube/qcheck#66]
I was trying to get a custom arbitrary (in a similar way as for the arbitrary tree example provided in Readme) and I found myself in need for something like the guard (or cond function) that can be found in the gasche random generator API that you mentioned. 
Shortly put, in QCheck.Gen I would need something like 
```ocaml 
val guard:  ('a -> bool) -> 'a Gen.t -> 'a Gen.t
```

that generates values satisfying the precondition given as argument.
For my specific case, I just need to generate non-zero small integers, which I guess can be done in another way (although I did not manage to find the right way yet, besides generating integer in a range excluding 0) but I am confident that more complicated use-cases could arise.

Such a function already exists for Shrink with filter, but I did not find anything for Gen.

If something like that already exists, or if there is another way I would be grateful if you would tell me where it can be found in the documentation :)

**Comment by c-cube** [comment]
`guard` as you present it is dangerous, as it might never terminate (if the generator doesn't produce values satisfying the predicate). Even with a bound, it implies generators can fail.

For non-zero small integers it's much simpler to use `1 -- 10` or something like that (or maybe the union of `(-10) -- (-1)` and `1 -- 10`, which would be a useful combinator?). For complicated use cases you can also put the precondition inside the test itself (with `assume` or `assume_fail`) so that it will also work after shrinking.

**Comment by nicoTolly** [comment]
Hi, first, thank you for your answer :)

I solved my problem the following way : 
```ocaml
    let non_zero_nat = QCheck.Gen.map (fun s -> if s = 0 then 1 else s) QCheck.Gen.small_nat 
```

As 1 is an acceptable parameter, this has the tiny inconvenient of a bit distorted distribution, but I can live with that. 

Otherwise, I am not entirely buying your argument, because it is already possible to have tests that never pass the precondition with assume. I saw an issue about throwing an error or a warning if that cornercase happens and I don't know what you decided. 

Wouldn't it make sense that the user would be responsible for passing realistic preconditions ? guard could fail after N attempts for a given N, for example. 
Anyway, thanks again for your work, this is a great library :)

**Comment by c-cube** [comment]
It's discussed in #55 and the default is to warn if few (or none) tests pass the precondition. It's possible to have the test entirely fail, as well.

**Comment by 7h3kk1d** [comment]
Chiming in on this old issue. I agree with @nicoTolly that there should be a way to fail this on the generator side rather than shift the distribution or fail precondition. If you're generating a large recursive structure you don't want to fail the entire attempt and I'd rather not mess up the distribution by special casing like above.
